In [93]:
import pandas as pd
import numpy as np

In [94]:
df = pd.read_csv("/Users/pranavsukumaran/Desktop/netflix/data/ViewingActivity.csv")

selected_profiles = ["Pranav", "Home", "Priya"]

# Filter the dataframe 
filtered_data = df[df['Profile Name'].isin(selected_profiles)]

In [95]:
filtered_data

,Profile Name,Start Time,Duration,Attributes,Title,Supplemental Video Type,Device Type,Bookmark,Latest Bookmark,Country
0,Home,2024-01-01 07:41:10,00:01:48,NaN,Burning Body: Limited Series: The Reservoir (E...,NaN,Xiaomi M19 Set Top Box,00:07:53,00:07:53,IN (India)
1,Home,2024-01-01 07:17:23,00:06:04,NaN,Burning Body: Limited Series: The Reservoir (E...,NaN,Xiaomi M19 Set Top Box,00:06:06,Not latest view,IN (India)
2,Home,2024-01-01 07:16:59,00:00:14,Autoplayed: user action: None;,Season 1 Villain / Antagonist Clip: Burning Body,HOOK,Xiaomi M19 Set Top Box,00:00:14,00:00:14,IN (India)
3,Home,2024-01-01 07:16:43,00:00:06,Autoplayed: user action: None;,Sajini Shinde Ka Viral Video (FKA Happy Teache...,HOOK,Xiaomi M19 Set Top Box,00:00:06,00:00:06,IN (India)
4,Home,2024-01-01 07:16:24,00:00:08,Autoplayed: user action: None;,Three of Us_hook_03_16x9,HOOK,Xiaomi M19 Set Top Box,00:00:08,00:00:08,IN (India)
...,...,...,...,...,...,...,...,...,...,...
19932,Priya,2016-10-07 22:09:57,00:00:06,NaN,Stranger Things: Season 1: Chapter Two: The We...,NaN,Chrome PC (Cadmium),00:00:06,Not latest view,GB (United Kingdom)
19933,Priya,2016-10-07 22:09:39,00:00:09,NaN,Stranger Things: Season 1: Chapter One: The Va...,NaN,Chrome PC (Cadmium),00:00:09,Not latest view,GB (United Kingdom)
19934,Priya,2016-10-06 21:10:50,00:04:49,NaN,Breaking Bad: Season 4: Face Off (Episode 13),NaN,Chrome PC (Cadmium),00:04:49,Not latest view,GB (United Kingdom)
19935,Priya,2016-10-06 21:07:26,00:00:03,NaN,Breaking Bad: Season 1: Pilot (Episode 1),NaN,Chrome PC (Cadmium),00:00:03,00:00:03,GB (United Kingdom)
19936,Priya,2016-06-15 10:28:24,00:41:24,NaN,Narcos: Season 1: Descenso (Episode 1),NaN,Chrome PC (Cadmium),00:41:24,Not latest view,US (United States)

In [96]:
# Convert 'Duration' from the format "HH:MM:SS" to timedelta
filtered_data.loc[:,'Duration'] = pd.to_timedelta(filtered_data['Duration'])

# Filter out all rows where duration is less than 5 minutes
# Make a copy of the DataFrame to ensure it's a standalone DataFrame
data_filtered = filtered_data.loc[filtered_data['Duration'] >= pd.Timedelta(minutes=5)].copy()

# Preprocess the titles and classify as TV Show or Movie
def preprocess_and_classify_title(title):
    main_title = title.split(':')[0].strip()
    content_type = 'TV Show' if 'Season' in title or 'Episode' in title or ':' in title else 'Movie'
    return main_title, content_type

# Apply the preprocessing function to the 'Title' column
titles_types = data_filtered['Title'].apply(preprocess_and_classify_title)
data_filtered.loc[:, 'Title'] = titles_types.apply(lambda x: x[0])
data_filtered.loc[:, 'Type'] = titles_types.apply(lambda x: x[1])

# Remove the unwanted columns
columns_to_remove = ['Attributes', 'Supplemental Video Type', 'Bookmark', 'Latest Bookmark']
data_filtered = data_filtered.drop(columns=columns_to_remove)

# Now your DataFrame is updated and ready for further analysis or export
data_filtered

,Profile Name,Start Time,Duration,Title,Device Type,Country,Type
1,Home,2024-01-01 07:17:23,0 days 00:06:04,Burning Body,Xiaomi M19 Set Top Box,IN (India),TV Show
7,Home,2023-12-30 11:08:22,0 days 00:08:40,The Girl from Oslo,Xiaomi M19 Set Top Box,IN (India),TV Show
8,Home,2023-12-30 10:33:56,0 days 00:33:41,The Girl from Oslo,Xiaomi M19 Set Top Box,IN (India),TV Show
10,Home,2023-12-30 10:08:21,0 days 00:14:20,The Girl from Oslo,Xiaomi M19 Set Top Box,IN (India),TV Show
11,Home,2023-12-30 07:29:25,0 days 00:19:18,The Girl from Oslo,Xiaomi M19 Set Top Box,IN (India),TV Show
...,...,...,...,...,...,...,...
19927,Priya,2016-11-12 01:09:00,0 days 00:30:41,Stranger Things,Chrome PC (Cadmium),GB (United Kingdom),TV Show
19929,Priya,2016-11-12 00:21:51,0 days 00:15:09,Stranger Things,Chrome PC (Cadmium),GB (United Kingdom),TV Show
19930,Priya,2016-10-07 23:12:22,0 days 00:22:45,Stranger Things,Chrome PC (Cadmium),GB (United Kingdom),TV Show
19931,Priya,2016-10-07 22:10:50,0 days 00:46:15,Stranger Things,Chrome PC (Cadmium),GB (United Kingdom),TV Show
19936,Priya,2016-06-15 10:28:24,0 days 00:41:24,Narcos,Chrome PC (Cadmium),US (United States),TV Show

In [99]:
data_filtered['Duration'] = pd.to_timedelta(data_filtered['Duration'])
# Apply the function to the 'Duration' column
data_filtered['Duration'] = data_filtered['Duration'].dt.total_seconds() / 3600

data_filtered

,Profile Name,Start Time,Duration,Title,Device Type,Country,Type
1,Home,2024-01-01 07:17:23,0.101111,Burning Body,Xiaomi M19 Set Top Box,IN (India),TV Show
7,Home,2023-12-30 11:08:22,0.144444,The Girl from Oslo,Xiaomi M19 Set Top Box,IN (India),TV Show
8,Home,2023-12-30 10:33:56,0.561389,The Girl from Oslo,Xiaomi M19 Set Top Box,IN (India),TV Show
10,Home,2023-12-30 10:08:21,0.238889,The Girl from Oslo,Xiaomi M19 Set Top Box,IN (India),TV Show
11,Home,2023-12-30 07:29:25,0.321667,The Girl from Oslo,Xiaomi M19 Set Top Box,IN (India),TV Show
...,...,...,...,...,...,...,...
19927,Priya,2016-11-12 01:09:00,0.511389,Stranger Things,Chrome PC (Cadmium),GB (United Kingdom),TV Show
19929,Priya,2016-11-12 00:21:51,0.252500,Stranger Things,Chrome PC (Cadmium),GB (United Kingdom),TV Show
19930,Priya,2016-10-07 23:12:22,0.379167,Stranger Things,Chrome PC (Cadmium),GB (United Kingdom),TV Show
19931,Priya,2016-10-07 22:10:50,0.770833,Stranger Things,Chrome PC (Cadmium),GB (United Kingdom),TV Show
19936,Priya,2016-06-15 10:28:24,0.690000,Narcos,Chrome PC (Cadmium),US (United States),TV Show

In [101]:

# Convert 'Start Time' to datetime
data_filtered['Start Time'] = pd.to_datetime(data_filtered['Start Time'])

# Now extract the components
data_filtered['Hour'] = data_filtered['Start Time'].dt.hour
data_filtered['Day'] = data_filtered['Start Time'].dt.day
data_filtered['Month'] = data_filtered['Start Time'].dt.month
data_filtered['Year'] = data_filtered['Start Time'].dt.year

In [102]:
data_filtered

,Profile Name,Start Time,Duration,Title,Device Type,Country,Type,Hour,Day,Month,Year
1,Home,2024-01-01 07:17:23,0.101111,Burning Body,Xiaomi M19 Set Top Box,IN (India),TV Show,7,1,1,2024
7,Home,2023-12-30 11:08:22,0.144444,The Girl from Oslo,Xiaomi M19 Set Top Box,IN (India),TV Show,11,30,12,2023
8,Home,2023-12-30 10:33:56,0.561389,The Girl from Oslo,Xiaomi M19 Set Top Box,IN (India),TV Show,10,30,12,2023
10,Home,2023-12-30 10:08:21,0.238889,The Girl from Oslo,Xiaomi M19 Set Top Box,IN (India),TV Show,10,30,12,2023
11,Home,2023-12-30 07:29:25,0.321667,The Girl from Oslo,Xiaomi M19 Set Top Box,IN (India),TV Show,7,30,12,2023
...,...,...,...,...,...,...,...,...,...,...,...
19927,Priya,2016-11-12 01:09:00,0.511389,Stranger Things,Chrome PC (Cadmium),GB (United Kingdom),TV Show,1,12,11,2016
19929,Priya,2016-11-12 00:21:51,0.252500,Stranger Things,Chrome PC (Cadmium),GB (United Kingdom),TV Show,0,12,11,2016
19930,Priya,2016-10-07 23:12:22,0.379167,Stranger Things,Chrome PC (Cadmium),GB (United Kingdom),TV Show,23,7,10,2016
19931,Priya,2016-10-07 22:10:50,0.770833,Stranger Things,Chrome PC (Cadmium),GB (United Kingdom),TV Show,22,7,10,2016
19936,Priya,2016-06-15 10:28:24,0.690000,Narcos,Chrome PC (Cadmium),US (United States),TV Show,10,15,6,2016

In [103]:
data_filtered.drop(columns="Start Time")

,Profile Name,Duration,Title,Device Type,Country,Type,Hour,Day,Month,Year
1,Home,0.101111,Burning Body,Xiaomi M19 Set Top Box,IN (India),TV Show,7,1,1,2024
7,Home,0.144444,The Girl from Oslo,Xiaomi M19 Set Top Box,IN (India),TV Show,11,30,12,2023
8,Home,0.561389,The Girl from Oslo,Xiaomi M19 Set Top Box,IN (India),TV Show,10,30,12,2023
10,Home,0.238889,The Girl from Oslo,Xiaomi M19 Set Top Box,IN (India),TV Show,10,30,12,2023
11,Home,0.321667,The Girl from Oslo,Xiaomi M19 Set Top Box,IN (India),TV Show,7,30,12,2023
...,...,...,...,...,...,...,...,...,...,...
19927,Priya,0.511389,Stranger Things,Chrome PC (Cadmium),GB (United Kingdom),TV Show,1,12,11,2016
19929,Priya,0.252500,Stranger Things,Chrome PC (Cadmium),GB (United Kingdom),TV Show,0,12,11,2016
19930,Priya,0.379167,Stranger Things,Chrome PC (Cadmium),GB (United Kingdom),TV Show,23,7,10,2016
19931,Priya,0.770833,Stranger Things,Chrome PC (Cadmium),GB (United Kingdom),TV Show,22,7,10,2016
19936,Priya,0.690000,Narcos,Chrome PC (Cadmium),US (United States),TV Show,10,15,6,2016

In [105]:
unique_devices = data_filtered['Device Type'].unique()

unique_devices

array(['Xiaomi M19 Set Top Box', 'Apple iPhone 13 Pro Max',
       'Chrome PC (Cadmium)', 'Edge OSS - Windows (Cadmium)',
       'iPad Air Cellular', 'iPad Air 2 WiFi', 'FireTV Stick 2016',
       'iPhone 12', 'Apple TV 3 (revised)',
       'Sony Sony Android TV 2016 M1 Smart TV',
       'Samsung 2018 Kant-S DTV 5.0 Smart TV',
       'Netflix Chrome MAC (Cadmium) HTML 5', 'Safari MAC (Cadmium)',
       'Xiaomi aquaman Streaming Stick',
       'Google Chromecast V3 Streaming Stick',
       'Apple iPad Pro 11in 2nd Gen (Wi-Fi/Cell) iPad', 'Apple iPhone 6s',
       'Apple Apple TV 4 Apple TV', 'iPhone 5S CDMA', 'Sony PS4',
       'Sony PS3', 'Apple iPad Pro 11in 2nd Gen (Wi-Fi) iPad',
       'Apple iPhone 11', 'TCL 2K18 FHD UnionTV Smart TV',
       'LG 2014 Mstar UHD TV', 'Roku Nemo Set Top Box',
       'Apple iPhone X (GSM)', 'Apple iPhone 7 Plus (GSM)'], dtype=object)

In [106]:
def categorize_device(device_name):
    device_name = device_name.lower()  # Convert to lowercase for case-insensitive matching
    if 'iphone' in device_name or 'ipad' in device_name:
        return 'Apple Mobile Devices'
    elif 'chrome' in device_name or 'edge' in device_name or 'safari' in device_name:
        return 'Web Browsers'
    elif 'android tv' in device_name or 'smart tv' in device_name or 'tv' in device_name:
        return 'Smart TVs'
    elif 'streaming stick' in device_name or 'chromecast' in device_name or 'firetv' in device_name or 'apple tv' in device_name or 'roku' in device_name:
        return 'Streaming Devices'
    elif 'ps4' in device_name or 'ps3' in device_name:
        return 'Game Consoles'
    elif 'set top box' in device_name:
        return 'Set Top Boxes'
    else:
        return 'Other'

In [108]:
# Assuming 'data_filtered' is your DataFrame and 'Device Type' is the column name
data_filtered['Device Category'] = data_filtered['Device Type'].apply(categorize_device)

# Now you can check the first few rows of your DataFrame to see the new 'Device Category' column
data_filtered

,Profile Name,Start Time,Duration,Title,Device Type,Country,Type,Hour,Day,Month,Year,Device Category
1,Home,2024-01-01 07:17:23,0.101111,Burning Body,Xiaomi M19 Set Top Box,IN (India),TV Show,7,1,1,2024,Set Top Boxes
7,Home,2023-12-30 11:08:22,0.144444,The Girl from Oslo,Xiaomi M19 Set Top Box,IN (India),TV Show,11,30,12,2023,Set Top Boxes
8,Home,2023-12-30 10:33:56,0.561389,The Girl from Oslo,Xiaomi M19 Set Top Box,IN (India),TV Show,10,30,12,2023,Set Top Boxes
10,Home,2023-12-30 10:08:21,0.238889,The Girl from Oslo,Xiaomi M19 Set Top Box,IN (India),TV Show,10,30,12,2023,Set Top Boxes
11,Home,2023-12-30 07:29:25,0.321667,The Girl from Oslo,Xiaomi M19 Set Top Box,IN (India),TV Show,7,30,12,2023,Set Top Boxes
...,...,...,...,...,...,...,...,...,...,...,...,...
19927,Priya,2016-11-12 01:09:00,0.511389,Stranger Things,Chrome PC (Cadmium),GB (United Kingdom),TV Show,1,12,11,2016,Web Browsers
19929,Priya,2016-11-12 00:21:51,0.252500,Stranger Things,Chrome PC (Cadmium),GB (United Kingdom),TV Show,0,12,11,2016,Web Browsers
19930,Priya,2016-10-07 23:12:22,0.379167,Stranger Things,Chrome PC (Cadmium),GB (United Kingdom),TV Show,23,7,10,2016,Web Browsers
19931,Priya,2016-10-07 22:10:50,0.770833,Stranger Things,Chrome PC (Cadmium),GB (United Kingdom),TV Show,22,7,10,2016,Web Browsers
19936,Priya,2016-06-15 10:28:24,0.690000,Narcos,Chrome PC (Cadmium),US (United States),TV Show,10,15,6,2016,Web Browsers

In [111]:
counts = data_filtered['Device Category'].value_counts()

counts

Device Category
Web Browsers            5179
Apple Mobile Devices    2985
Set Top Boxes           1735
Smart TVs               1659
Streaming Devices        138
Game Consoles             21
Name: count, dtype: int64

In [112]:
data_filtered.drop(columns="Device Type")

,Profile Name,Start Time,Duration,Title,Country,Type,Hour,Day,Month,Year,Device Category
1,Home,2024-01-01 07:17:23,0.101111,Burning Body,IN (India),TV Show,7,1,1,2024,Set Top Boxes
7,Home,2023-12-30 11:08:22,0.144444,The Girl from Oslo,IN (India),TV Show,11,30,12,2023,Set Top Boxes
8,Home,2023-12-30 10:33:56,0.561389,The Girl from Oslo,IN (India),TV Show,10,30,12,2023,Set Top Boxes
10,Home,2023-12-30 10:08:21,0.238889,The Girl from Oslo,IN (India),TV Show,10,30,12,2023,Set Top Boxes
11,Home,2023-12-30 07:29:25,0.321667,The Girl from Oslo,IN (India),TV Show,7,30,12,2023,Set Top Boxes
...,...,...,...,...,...,...,...,...,...,...,...
19927,Priya,2016-11-12 01:09:00,0.511389,Stranger Things,GB (United Kingdom),TV Show,1,12,11,2016,Web Browsers
19929,Priya,2016-11-12 00:21:51,0.252500,Stranger Things,GB (United Kingdom),TV Show,0,12,11,2016,Web Browsers
19930,Priya,2016-10-07 23:12:22,0.379167,Stranger Things,GB (United Kingdom),TV Show,23,7,10,2016,Web Browsers
19931,Priya,2016-10-07 22:10:50,0.770833,Stranger Things,GB (United Kingdom),TV Show,22,7,10,2016,Web Browsers
19936,Priya,2016-06-15 10:28:24,0.690000,Narcos,US (United States),TV Show,10,15,6,2016,Web Browsers